name = "who-when-visualization"
main = "src/entry.py"
compatibility_date = "2026-04-06"
compatibility_flags = ["python_workers"]
workers_dev = true

[vars]
BASE_PATH = "/who_when"
DEFAULT_DATASET_LANG = "cn"

[[routes]]
pattern = "vis.102465.xyz/who_when*"
zone_name = "102465.xyz"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/who_when*"]
